# Generated by Django 5.2 on 2025-04-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('computer_name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('username', models.CharField(max_length=100)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
            ],
        ),
    ]
